### ISSUE TITLE
Can install firefox

### ISSUE THREAD

**Issue by Greenarrow4245** [Yisus7u7/termux-desktop-xfce#113]
Cannot install firefox otter-browser sucks

**Comment by Jyannz** [comment]
You can use proot-distro.
Here is how to install firefox

1. apt update
2. apt upgrade
3. apt install proot-distro -y
4. proot-distro install ubuntu
5. proot-distro login ubuntu
6. apt update
7. apt upgrade
8. apt install firefox

This issue was already solved. Try taking a look at closed issues. I forgot which one, but this was solved months ago.

**Comment by Jyannz** [comment]
Issue #21 and #22 will be useful for you. In issue #21 there are a list of commands to actually run firefox and other apps so this would help you a lot. You can close this issue now.

**Comment by Yisus7u7** [comment]
Done!.

run:  `pkg install firefox`
