### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by GeekMan44** [Yisus7u7/termux-desktop-xfce#115]
Hi I'm not sure if I need to use proot-distro or not because when I do vncserver on termux it launch but on proot-distro that give me a black screen
And when I vncserver in termux my screen is bug 
![Screenshot_2022-11-04-09-42-45-730_com realvnc viewer android](https://user-images.githubusercontent.com/93622316/199930087-ad3abe25-ca2f-4148-b7c8-a29ba5914e50.jpg)
Thanks for reading that

**Comment by GeekMan44** [comment]
I fix the problem with the screen bug

**Comment by Jyannz** [comment]
@GeekMan44 What VNC Viewer are you using? This is a bug in your VNC Viewer, I suggest using [NetHunter KeX](https://store.nethunter.com/repo/com.offsec.nethunter.kex_11407306.apk). VNC Viewer automatically lowers the quality to improve performance. To fix this, simply go to settings and **Change Picture Quality** from **Automatic** to **High**, that should fix your problem. This issue is now solved, you can close this issue now.

**Comment by Jyannz** [comment]
@GeekMan44 If you have any other issues, ask away:)

@Yisus7u7 You can close this issue now.
