### ISSUE TITLE
Desktop Issue

### ISSUE THREAD

**Issue by JyanJohn** [Yisus7u7/termux-desktop-xfce#65]
Hello again, I have a issue with the panel and I cant do anything but view the text files and open thunar...
![Screenshot_20211214_103657](https://user-images.githubusercontent.com/86553521/145923146-554f83ec-b4f0-4394-b1cd-410c27c692ff.jpg)

**Comment by Yisus7u7** [comment]
This problem is not from termux-desktop-xfce, if not directly from termux, this happens because the glib version was updated, and now it brings many errors, we have to wait for it to be solved, the solution for now is to downgrade glib to the previous version, there is also a problem with shared-mime-info, see (https://github.com/termux/x11-packages/issues/520)

**Comment by das-rob3rt** [comment]
> This problem is not from termux-desktop-xfce, if not directly from termux, this happens because the glib version was updated, and now it brings many errors, we have to wait for it to be solved, the solution for now is to downgrade glib to the previous version, there is also a problem with shared-mime-info, see (https://github.com/termux/x11-packages/issues/520)

Could you pls provide a guide on how to downgrade `glib`, in order to temporarily work this around? Appreciated.

**Comment by JyanJohn** [comment]
@Yisus7u7 I got it working! But another issue emerges, xfce4-terminal is not working, I reinstalled it a bunch of times and it is still not working so I replaced the default terminal emulator with QTerminal.

**Comment by Yisus7u7** [comment]
> @Yisus7u7 I got it working! But another issue emerges, xfce4-terminal is not working, I reinstalled it a bunch of times and it is still not working so I replaced the default terminal emulator with QTerminal.

that's because libvte is broken, it will be fixed soon.
